version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.25
    ports:
      - "6831:6831/udp"
      - "16686:16686"
